//! For tests only (feature `testing`): a throwaway database per test, and signed batches.
//!
//! `DATABASE_URL` names a Postgres server the tests may `CREATE DATABASE` on; each test gets
//! its own `panel_test_<uuid>` database there, dropped when it ends, and never touches the
//! database the URL names. Without `DATABASE_URL` a database test is skipped, and says so
//! under `--nocapture`.
//!
//! Skipped under CI too, for now: the workflows are generated by v_flakes and give the
//! runner no Postgres, so failing there would only make every run red. Until they do, a
//! green CI run has not exercised the database — run these locally.

use std::str::FromStr;

use jiff::Timestamp;
use panel_core::signature;
use serde_json::{Value, json};
use sqlx::{
	Connection, Executor, PgConnection,
	postgres::{PgConnectOptions, PgPoolOptions},
};
use uuid::Uuid;

use crate::{Panel, seal::DataKey, store::Store};

/// A database that lives as long as this value.
pub struct TestDb {
	admin: PgConnectOptions,
	name: String,
	pub options: PgConnectOptions,
}

impl TestDb {
	/// A fresh, empty database; `None` when there is no server to make it on.
	pub async fn create() -> Option<Self> {
		let Some(url) = std::env::var("DATABASE_URL").ok().filter(|v| !v.is_empty()) else {
			eprintln!("SKIPPED: DATABASE_URL unset — this test asserted nothing");
			return None;
		};
		let admin = PgConnectOptions::from_str(&url).expect("DATABASE_URL is a Postgres URL");
		let name = format!("panel_test_{}", Uuid::now_v7().simple());
		let mut conn = PgConnection::connect_with(&admin).await.expect("connecting to DATABASE_URL");
		// The name is ours (a UUID's hex), not input: safe to splice into the statement.
		conn.execute(sqlx::AssertSqlSafe(format!("CREATE DATABASE {name}"))).await.expect("creating a test database");
		conn.close().await.expect("closing the admin connection");
		let options = admin.clone().database(&name);
		Some(Self { admin, name, options })
	}

	/// A connected store on this database, migrated first.
	pub async fn store(&self) -> Store {
		Store::migrate(self.options.clone()).await.expect("migrating the test database");
		Store::connect_with(self.options.clone()).await.expect("connecting to the test database")
	}

	/// A plain pool on this database, for assertions the engine has no API for.
	pub async fn pool(&self) -> sqlx::PgPool {
		PgPoolOptions::new()
			.max_connections(2)
			.connect_with(self.options.clone())
			.await
			.expect("connecting to the test database")
	}
}

impl Drop for TestDb {
	fn drop(&mut self) {
		// Drop runs outside any async context, and the test's runtime may already be gone,
		// so the database is dropped from a runtime of its own on a thread of its own.
		let admin = self.admin.clone();
		let name = self.name.clone();
		let dropped = std::thread::spawn(move || {
			let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().expect("a runtime to drop the test database");
			rt.block_on(async move {
				let mut conn = PgConnection::connect_with(&admin).await?;
				conn.execute(sqlx::AssertSqlSafe(format!("DROP DATABASE IF EXISTS {name} WITH (FORCE)"))).await?;
				conn.close().await
			})
		})
		.join();
		if !matches!(dropped, Ok(Ok(()))) {
			eprintln!("could not drop test database {}: {dropped:?}", self.name);
		}
	}
}

/// A panel on a fresh store with a fresh data key.
pub async fn panel(db: &TestDb) -> Panel {
	let key = DataKey::from_hex(&DataKey::generate_hex().expect("random")).expect("a fresh key");
	Panel::new(db.store().await, key)
}

/// A request as a source sends it: the body, and the headers' values.
pub struct Signed {
	pub key_id: String,
	pub timestamp: String,
	pub signature: String,
	pub body: Vec<u8>,
}

impl Signed {
	pub fn batch(&self) -> crate::SignedBatch<'_> {
		crate::SignedBatch {
			key_id: &self.key_id,
			timestamp: &self.timestamp,
			signature: &self.signature,
			body: &self.body,
		}
	}
}

/// `{"events": events}`, signed at `at` with `secret`.
pub fn sign(key_id: &str, secret: &str, events: &[Value], at: Timestamp) -> Signed {
	let body = serde_json::to_vec(&json!({ "events": events })).expect("JSON");
	let timestamp = at.as_second().to_string();
	Signed {
		key_id: key_id.to_owned(),
		signature: signature::sign(secret.as_bytes(), &timestamp, &body),
		timestamp,
		body,
	}
}

/// An event as a source writes it, with a fresh id.
pub fn event(r#type: &str, occurred_at: Timestamp, kind: &str, subject: Value, properties: Value) -> Value {
	json!({
		"id": Uuid::now_v7().to_string(),
		"schema": "sa.funnel.v1",
		"type": r#type,
		"typeVersion": 1,
		"occurredAt": occurred_at.to_string(),
		"source": {"kind": kind, "id": "test"},
		"subject": subject,
		"properties": properties,
	})
}
