// AUTO-GENERATED by `nix run .#gen` — do not edit.

export const STAGES = ["created", "contacted", "quoted", "won", "completed", "paid", "lost"] as const;
export type Stage = (typeof STAGES)[number];

export const SUSPECTS = ["rate_limited", "too_fast"] as const;
export type Suspect = (typeof SUSPECTS)[number];

export const FLOWS = ["quote", "estimate", "fixed"] as const;
export type Flow = (typeof FLOWS)[number];

export const BOOKING_STATUSES = ["none", "requested", "booked", "canceled", "done", "no_show"] as const;
export type BookingStatus = (typeof BOOKING_STATUSES)[number];

export const BOOKING_MATCHES = ["ref", "contact", "manual"] as const;
export type BookingMatch = (typeof BOOKING_MATCHES)[number];

export const DAY_PARTS = ["morning", "afternoon", "evening"] as const;
export type DayPart = (typeof DAY_PARTS)[number];

export const QUOTE_CURRENCY = "EUR";

export const CONTACT_SLA_SECONDS = 1800;
