// AUTO-GENERATED by `nix run .#gen` — do not edit.

export const SOURCE_KINDS = ["site", "review_archive", "gbp", "posthog", "panel", "sheet", "telephony", "booking"] as const;
export type SourceKind = (typeof SOURCE_KINDS)[number];

export const KEYED_SOURCE_KINDS = ["site", "review_archive", "gbp", "posthog", "sheet", "telephony"] as const;
export type KeyedSourceKind = (typeof KEYED_SOURCE_KINDS)[number];
