// AUTO-GENERATED by `nix run .#gen` — do not edit.

/**
 * The signed-in user of an `/api/v1` request, put in its extensions by the gate; `GET /me`.
 */
export type Caller = { user_id: string, email: string, preferred_name: string, 
/**
 * Concrete `sa` permissions, as concierge resolved them.
 */
permissions: Array<Permission>, 
/**
 * Signed in by `PANEL_DEV_SIGN_IN`, not concierge: `/me` says so, for the UI to show.
 */
dev_sign_in: boolean, 
/**
 * Where the account itself is managed, on concierge's origin; none under dev sign-in.
 */
account_center: string | null, };

/**
 * An access request of the caller's, standing.
 */
export type AccessRequest = { 
/**
 * A permission or an alias of the `sa` catalog.
 */
need: Permission | keyof typeof ALIASES, 
/**
 * RFC 3339.
 */
requested_at: string, };

export const PERMISSIONS = ["sa:admin:sources:manage", "sa:analysis:experiments:edit", "sa:analysis:read", "sa:playbook:mcp:use", "sa:review_archive:archive:operate", "sa:review_archive:members:act_as", "sa:review_archive:tokens:grant", "sa:work:leads:edit", "sa:work:pii:see", "sa:work:places:edit", "sa:work:pricing:edit", "sa:work:read"] as const;
export type Permission = (typeof PERMISSIONS)[number];

export const ALIASES = {
  "sa:admin": ["sa:admin:sources:manage", "sa:analysis:experiments:edit", "sa:analysis:read", "sa:playbook:mcp:use", "sa:review_archive:archive:operate", "sa:review_archive:members:act_as", "sa:review_archive:tokens:grant", "sa:work:leads:edit", "sa:work:pii:see", "sa:work:places:edit", "sa:work:pricing:edit", "sa:work:read"],
  "sa:operator": ["sa:analysis:read", "sa:work:leads:edit", "sa:work:pii:see", "sa:work:read"],
} as const;
