// AUTO-GENERATED by `nix run .#gen` — do not edit.

/**
 * The signed-in user of an `/api/v1` request, put in its extensions by [`gate`]; `GET /me`.
 */
export type Caller = { user_id: string, role: Role, email: string, preferred_name: string, 
/**
 * Signed in by `PANEL_DEV_SIGN_IN`, not concierge: `/me` says so, for the UI to show.
 */
dev_sign_in: boolean, };
/**
 * Ordered by what they may do: each role may do everything the one before it may.
 */
export type Role = "operator" | "admin";

export const ROLES = ["operator", "admin"] as const;

export const MAY = {
  "admin": { "edits_experiments": true, "edits_leads": true, "edits_places": true, "edits_pricing": true, "manages_sources": true, "sees_pii": true },
  "operator": { "edits_experiments": false, "edits_leads": true, "edits_places": false, "edits_pricing": false, "manages_sources": false, "sees_pii": true },
} as const;
