//! The panel's wire contract, `sa.funnel.v1`, generated from `contracts/proto/sa/v1`.
//!
//! Every message has prost (binary) and serde (protojson, via pbjson) impls; the HTTP
//! ingest speaks the latter. Nothing here validates beyond the JSON shape: what a field may
//! hold is the panel's to check.

/// `package sa.v1`.
// Generated by prost and pbjson at build time: its style is theirs, and a lint there has
// no fix we could keep (the next build writes it again).
#[allow(clippy::all)]
pub mod v1 {
	include!(concat!(env!("OUT_DIR"), "/sa.v1.rs"));
	include!(concat!(env!("OUT_DIR"), "/sa.v1.serde.rs"));
}

pub use pbjson_types;

/// The `schema` every `sa.funnel.v1` event carries.
pub const SCHEMA: &str = "sa.funnel.v1";

#[cfg(test)]
mod tests {
	use super::v1::{Event, PaymentReceivedV1};

	#[test]
	fn protojson_in_both_spellings() {
		let camel: Event = serde_json::from_value(serde_json::json!({
			"id": "0192f0c1-7b3a-7c2e-9d4f-1a2b3c4d5e6f",
			"schema": "sa.funnel.v1",
			"type": "lead.created",
			"typeVersion": 1,
			"occurredAt": "2026-09-30T10:00:00Z",
			"source": {"kind": "site", "id": "aquafix"},
			"subject": {"brandId": "aquafix", "leadId": "L-1"},
			"properties": {"channel": "form"},
			"pii": {"phone": "+33 6 00 00 00 00"}
		}))
		.unwrap();
		let snake: Event = serde_json::from_value(serde_json::json!({
			"id": "0192f0c1-7b3a-7c2e-9d4f-1a2b3c4d5e6f",
			"schema": "sa.funnel.v1",
			"type": "lead.created",
			"type_version": 1,
			"occurred_at": "2026-09-30T10:00:00Z",
			"source": {"kind": "site", "id": "aquafix"},
			"subject": {"brand_id": "aquafix", "lead_id": "L-1"},
			"properties": {"channel": "form"},
			"pii": {"phone": "+33 6 00 00 00 00"}
		}))
		.unwrap();
		assert_eq!(camel, snake);
		assert_eq!(camel.occurred_at.unwrap().seconds, 1_790_762_400);
		assert_eq!(camel.subject.unwrap().lead_id.as_deref(), Some("L-1"));
	}

	#[test]
	fn int64_as_string_or_number_and_unknown_fields_refused() {
		let a: PaymentReceivedV1 = serde_json::from_value(serde_json::json!({"billed": "12000", "commission": 1800, "currency": "EUR"})).unwrap();
		assert_eq!((a.billed, a.commission), (12_000, 1_800));
		assert!(serde_json::from_value::<PaymentReceivedV1>(serde_json::json!({"billed": 1, "tip": 2})).is_err());
	}
}
